# Generated by Django 5.0.3 on 2024-07-17 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('images', models.ImageField(upload_to='cakes/')),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('images', models.ImageField(upload_to='cakes/')),
            ],
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('images', models.ImageField(upload_to='cakes/')),
            ],
        ),
        migrations.CreateModel(
            name='Trappuccino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('images', models.ImageField(upload_to='cakes/')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffees_quantity', models.PositiveIntegerField(default=0)),
                ('traps_quantity', models.PositiveIntegerField(default=0)),
                ('cakes_quantity', models.PositiveIntegerField(default=0)),
                ('sands_quantity', models.PositiveIntegerField(default=0)),
                ('cakes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cake')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
                ('coffees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.coffee')),
                ('sandwiches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.sandwich')),
                ('trappuccinos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.trappuccino')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cakes',
            field=models.ManyToManyField(through='shop.CartItem', to='shop.cake'),
        ),
        migrations.AddField(
            model_name='cart',
            name='coffees',
            field=models.ManyToManyField(through='shop.CartItem', to='shop.coffee'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffees_quantity', models.PositiveIntegerField()),
                ('traps_quantity', models.PositiveIntegerField(default=0)),
                ('cakes_quantity', models.PositiveIntegerField(default=0)),
                ('sands_quantity', models.PositiveIntegerField()),
                ('cakes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cake')),
                ('coffees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.coffee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('sandwiches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.sandwich')),
                ('trappuccinos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.trappuccino')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cakes',
            field=models.ManyToManyField(through='shop.OrderItem', to='shop.cake'),
        ),
        migrations.AddField(
            model_name='order',
            name='coffees',
            field=models.ManyToManyField(through='shop.OrderItem', to='shop.coffee'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='sands',
            field=models.ManyToManyField(through='shop.OrderItem', to='shop.sandwich'),
        ),
        migrations.AddField(
            model_name='cart',
            name='sands',
            field=models.ManyToManyField(through='shop.CartItem', to='shop.sandwich'),
        ),
        migrations.AddField(
            model_name='order',
            name='traps',
            field=models.ManyToManyField(through='shop.OrderItem', to='shop.trappuccino'),
        ),
        migrations.AddField(
            model_name='cart',
            name='traps',
            field=models.ManyToManyField(through='shop.CartItem', to='shop.trappuccino'),
        ),
    ]
