# Generated by Django 5.0.3 on 2024-07-18 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cakes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cake'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='coffees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.coffee'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sandwiches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sandwich'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='trappuccinos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.trappuccino'),
        ),
    ]
